image: alpine:latest

stages:
  - build
  - test
  - deploy # dummy stage to follow the template guidelines
  - review
  - staging
  - canary
  - production
  - performance
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - cleanup

include:
  - template: Jobs/Build.gitlab-ci.yml
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - template: Jobs/Deploy.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml


test:
  stage: test
  image: "python:3.9"
  before_script:
    - pip install -r requirements.txt
  script:
    - python -m pytest

coverage:
    stage: test
    image: "python:3.9"
    before_script:
      - pip install -r requirements.txt
      - pip install pytest
      - pip install coverage
    script:
        - coverage run -m pytest
        - coverage xml
        - coverage html
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
    artifacts:
      reports:
        cobertura: coverage.xml
      paths:
        - htmlcov/


pages:
  stage: deploy
  dependencies:
    - coverage
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

deploy:
  stage: deploy
  image: "python:3.9"
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - pip install twine
    - python setup.py sdist
    - twine upload dist/*
  only:
    - tags